namespace NpgsqlRest.DartClient;

public class DartClientOptions
{
    /// <summary>
    /// File path for the generated code. Set to null to skip the code generation. Use {0} to set schema (or module) name when BySchema is true.
    /// </summary>
    public string? FilePath { get; set; } = null!;

    /// <summary>
    /// Force file overwrite.
    /// </summary>
    public bool FileOverwrite { get; set; } = false;

    /// <summary>
    /// Include current host information in the baseUrl variable.
    /// </summary>
    public bool IncludeHost { get; set; } = false;

    /// <summary>
    /// Set the custom host prefix information.
    /// </summary>
    public string? CustomHost { get; set; } = null;

    /// <summary>
    /// Adds comment header above each request based on PostgreSQL routine.
    /// Set None to skip.
    /// Set Simple (default) to add name, parameters and return values to comment header.
    /// Set Full to add the entire routine code as comment header.
    /// </summary>
    public CommentHeader CommentHeader { get; set; } = CommentHeader.Simple;

    /// <summary>
    /// When CommentHeader is set to Simple or Full, set to true to include routine comments in comment header.
    /// </summary>
    public bool CommentHeaderIncludeComments { get; set; } = true;

    /// <summary>
    /// Set to true to wrap responses as ApiResult&lt;T&gt; carrying status code, response and error.
    /// </summary>
    public bool IncludeStatusCode { get; set; } = false;

    /// <summary>
    /// Create files by PostgreSQL schema. File name will use formatted FilePath where {0} is the schema name in snake case.
    /// </summary>
    public bool BySchema { get; set; } = false;

    /// <summary>
    /// Emit request/response (and composite) model classes into a separate {name}_models.dart file.
    /// The client file imports and re-exports the models file so consumers keep a single import.
    /// </summary>
    public bool SeparateModelsFile { get; set; } = false;

    /// <summary>
    /// Lines to add to each header. {0} format placeholder is current timestamp.
    /// </summary>
    public List<string> HeaderLines { get; set; } = ["// autogenerated at {0}", "", ""];

    /// <summary>
    /// Dart import URI that provides a top-level `baseUrl` String variable, instead of defining it in the module.
    /// Example: "package:my_app/base_url.dart".
    /// </summary>
    public string? ImportBaseUrlFrom { get; set; } = null;

    /// <summary>
    /// Array of routine names to skip (without schema).
    /// </summary>
    public string[] SkipRoutineNames { get; set; } = [];

    /// <summary>
    /// Array of generated function names to skip (without schema).
    /// </summary>
    public string[] SkipFunctionNames { get; set; } = [];

    /// <summary>
    /// Array of url paths to skip.
    /// </summary>
    public string[] SkipPaths { get; set; } = [];

    /// <summary>
    /// Array of schema names to skip.
    /// </summary>
    public string[] SkipSchemas { get; set; } = [];

    /// <summary>
    /// Default Dart type for JSON values (columns and parameters of json/jsonb type).
    /// </summary>
    public string DefaultJsonType { get; set; } = "dynamic";

    /// <summary>
    /// Use routine name instead of endpoint name when generating a function name.
    /// </summary>
    public bool UseRoutineNameInsteadOfEndpoint { get; set; } = false;

    /// <summary>
    /// Emit top-level {name}Url functions that build the request URL.
    /// </summary>
    public bool ExportUrls { get; set; } = false;

    /// <summary>
    /// Keep Dart models unique, meaning, models with same fields and types will be merged into one model with the name of the first model. Significantly reduces number of generated models.
    /// </summary>
    public bool UniqueModels { get; set; } = false;

    /// <summary>
    /// Name of the header to use for XSRF token in upload requests. Set to null to skip.
    /// </summary>
    public string? XsrfTokenHeaderName { get; set; } = null;

    /// <summary>
    /// Emit public create{Name}EventSource factory functions for streaming (SSE) endpoints.
    /// When false, the factories are emitted with a private (underscore) name and only used internally.
    /// </summary>
    public bool ExportEventSources { get; set; } = true;

    /// <summary>
    /// Include optional named parameter `Uri Function(Uri uri)? parseUrl` that can rewrite the constructed URI before the request is made.
    /// </summary>
    public bool IncludeParseUrlParam { get; set; } = false;

    /// <summary>
    /// Include optional named parameter `http.Request Function(http.Request request)? parseRequest`
    /// (or `http.MultipartRequest Function(http.MultipartRequest multipart)? parseRequest` for uploads)
    /// that can rewrite the constructed request before it is sent.
    /// </summary>
    public bool IncludeParseRequestParam { get; set; } = false;

    /// <summary>
    /// List of custom imports to add to the generated code. It adds a line to a file. Use full expression like `import 'package:my_app/my_type.dart';`.
    /// </summary>
    public string[] CustomImports { get; set; } = [];

    /// <summary>
    /// List of custom headers to add to each request in generated code. Header value is inserted verbatim (include quotes for literals).
    /// </summary>
    public Dictionary<string, string> CustomHeaders { get; set; } = [];

    /// <summary>
    /// When true, include PostgreSQL schema name in the generated names to avoid name collisions. Set to false to simplify names when no name collisions are expected.
    /// </summary>
    public bool IncludeSchemaInNames { get; set; } = false;

    /// <summary>
    /// Name for the generated error class carrying problem-details responses.
    /// Only used when IncludeStatusCode is true.
    /// Default is "ApiError".
    /// </summary>
    public string ErrorTypeName { get; set; } = "ApiError";

    /// <summary>
    /// Name for the generated generic result class: {ResultTypeName}&lt;T&gt; with status, response and error fields.
    /// Only used when IncludeStatusCode is true.
    /// Default is "ApiResult".
    /// </summary>
    public string ResultTypeName { get; set; } = "ApiResult";

    /// <summary>
    /// When true, parameters that are filled by the server and cannot be set by the client are omitted
    /// from the generated request class, query string, and body. This covers automatic parameters
    /// that are also optional: HTTP Custom Type fields, resolved-parameter expressions, upload metadata,
    /// and — on endpoints that use user parameters — IP-address and user-claim parameters. A client value
    /// for these would be overridden server-side, so emitting them is misleading. Default is false
    /// (all parameters are emitted, preserving existing generated output).
    /// </summary>
    public bool OmitAutomaticParameters { get; set; } = false;

    /// <summary>
    /// Prefix for generated model class names.
    /// </summary>
    public string ModelPrefix { get; set; } = "";

    /// <summary>
    /// Suffix for generated model class names.
    /// </summary>
    public string ModelSuffix { get; set; } = "";

    /// <summary>
    /// When true (default), date, timestamp and timestamptz values map to Dart DateTime
    /// (parsed with DateTime.parse, serialized with toIso8601String). When false, they map to String.
    /// </summary>
    public bool UseDateTimeType { get; set; } = true;
}
