FROM ubuntu:25.04
WORKDIR /app
COPY NpgsqlRestClient /usr/local/bin/npgsqlrest

RUN apt-get update && \
    apt-get install -y --no-install-recommends libssl3 libgssapi-krb5-2 ca-certificates && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get clean autoclean && \
    apt-get autoremove --yes && \
    rm -rf /var/lib/{apt,dpkg,cache,log}/

ENV PATH="/usr/local/bin:${PATH}"

ENTRYPOINT ["npgsqlrest"]
